name: 'Android'
on:
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Setup Android SDK
        uses: amyu/setup-android@v3.1

      - name: Echo
        run: |
          sdkmanager --install emulator
          sdkmanager --install "system-images;android-31;default;x86_64"
          avdmanager -s create avd -n android_emulator_name -k "system-images;android-31;default;x86_64"
          ls -a $ANDROID_HOME
          echo '------------'
          ls -a ~/.android
