name: "Android"
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Build:
    runs-on: macos-13
    steps:
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Setup Android SDK
        uses: amyu/setup-android@v3.1

      - name: Echo
        run: |
          ls -a $ANDROID_HOME
          echo '------------'
          ls -a ~/.android
          echo '------------'
          ls -a ~

      - name: list avd
        run: avdmanager list avd
      - name: list images
        run: sdkmanager --list
      - name: install image
        run: sdkmanager --install 'system-images;android-31;default;x86_64'
      - name: create avd
        run: avdmanager -s create avd -n TestCreate_12345 -k 'system-images;android-31;default;x86_64' --force
      - name: list avd
        run: avdmanager list avd
      - name: start avd
        run: "$ANDROID_HOME/emulator/emulator -verbose -avd TestCreate_12345 -noaudio -no-boot-anim -no-snapshot -no-snapshot-save -no-window -gpu swiftshader_indirect"
