name: "Android"
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Build:
    runs-on: macos-latest
    steps:
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Setup Android SDK
        uses: amyu/setup-android@v3.1

      - name: Echo
        run: |
          ls -a $ANDROID_HOME
          echo '------------'
          ls -a ~/.android
          echo '------------'
          ls -a ~

      - name: list avd
        run: avdmanager list avd
      - name: list images
        run: sdkmanager --list
      - name: install image
        run: sdkmanager --install 'system-images;android-31;target;arm64-v8a'
      - name: create avd
        run: avdmanager -s create avd -n TestCreate_12345 -k 'system-images;android-31;target;arm64-v8a'
