name: 'Build'
on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
         env:
           GITHUB_CONTEXT: ${{ toJson(github) }}
         run: |
           echo "${{ github.sha }}"
           echo "${{ github.sha }}"
           echo "${{ github.event.pull_request.head.sha }}"
           echo "$GITHUB_CONTEXT"| jq '.event.commits[].id' | tail -2 | head -1 |sed 's/\"//g'

      - name: Marged
          if: github.event.pull_request.merged == true
         run: |
          echo "${{ github.sha }}"
          echo "${{ github.sha }}"
          echo "${{ github.event.pull_request.head.sha }}"