name: 'Merged'
on:
  pull_request:
    types: closed
    branches:
      - main

jobs:
  Merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "${{ github.sha }}"
          echo "${{ github.event.pull_request.head.sha }}"
          echo "${{ github.event.pull_request.base.sha }}"
          ls ~

      - name: Download apk artifact
        uses: actions/download-artifact@v3
        with:
          name: artifact-${{ github.event.pull_request.head.sha }}
          path: ~/

      - name: list files
        run: |
          ls ~

      - name: Archive apk artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact-${{ github.sha }}
          path: ~/commit.txt
          if-no-files-found: error
