name: 'Release'
on:
  push:
    tags:
      - 'v*'

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "${{ github.sha }}"
          echo "${{ github.event.pull_request.head.sha }}"
          echo "${{ github.event.pull_request.base.sha }}"
