name: 'Xcode'
on:
  push:
    branches:
      - main

jobs:
  Xcode:
    runs-on: macos-13
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - run: |
          ls -a /Applications/
          sudo xcode-select -s "/Applications/Xcode_15.0.app"
          xcrun simctl list | grep "iPhone 15"
          # bash ./xcode.sh
